### ISSUE TITLE
Failure Can Cause Subsequent Projects To Not Be Attempted

### ISSUE THREAD

**Issue by pennah** [ashur/pug#3]
### Summary 
* When I added a bunch of projects and ran `pug up all` the first project failed authentication. The rest appeared to not be even attempted. I believe they should have been.

### Steps to reproduce 

1. have a bunch of repos with varied remotes
2. add 'em to pug
3. contrive the scenario for the first to fail
4. run `pug update all` 

### Results expected 
* first one bounces, the rest get tried

### Actual results 
* first repo failed and that was the end of that

### Frequency 
- Repeatable? I think.

### Evidence
* This was the message which was not 100% accurate `pug: No supported version control found at '/Users/pena/Documents/dev/pennah.github.io'` 

### Personal Notes 
* Hiiiiiii. Thank you for making this. :raised_hands:

**Comment by ashur** [comment]
Hi Sheree!

I _think_ things are all squared away in the [latest release](https://github.com/ashur/pug/releases/tag/v0.3.1). Let me know when you (inevitably) uncover more weirdness :cold_sweat: or have any ideas on how it could be better.

Thanks!
